####################################################################
####################################################################
########    NITE makefile for personal usage                ########
########    Created by Gábor Pál (pal.gabor89@gmail.com)    ########
########    Date: 2012. 11. 06.                             ########
####################################################################
####################################################################

# Set your NITE home to this variable. You have to store your Common, Include, Lib, etc. libraries under this directory.
NITE_LIB_HOME = /home/palgabor/kinect/openni/prog/NITELib


# You can modify these variables depending on your project or your needs.
BIN_DIR = .
SRC_FILES = source/*.cpp
EXE_NAME = DrawGame


# Common stuff, do not change it unless you have good reason for it.
USED_LIBS += glut OpenNI XnVNite_1_5_2
DEFINES += USE_GLUT
INC_DIRS = $(NITE_LIB_HOME)/Include =/usr/include/ni
include $(NITE_LIB_HOME)/Common/CommonCppMakefile	



